### ISSUE TITLE
RedisConfig uses default value

### ISSUE THREAD

**Issue by devzorg** [jxskiss/ssl-cert-server#11]
```openresty-ssl-server-1  | 2022-09-15T11:26:55.775Z      ERROR   server  server/server.go:94     failed get certificate, typ= ACME_ON_DEMAND, name= *******.info {"error": "dial tcp 127.0.0.1:6379: connect: connection refused"}```

but it defined as
```
storage:
  type: "redis"  # or redis
  dir_cache: "/app/storage"
  redis:
    addr: "redis:6379"
    prefix: ""
```
please also add DB in struct to make possible choose db index, and may some more options like password and etc able in default lib of redis
